### ISSUE TITLE
Can't receive any email

### ISSUE THREAD

**Issue by UnMars** [0x178F/YandexMail-Account-Creator#3]
Hey!
Amazing project, works flawlessly but the mails I create can't receive or send any email and they finish by being blocked by yandex.
Is there a workaround or other mail providers where we can do the same but without phone verification?

**Comment by 0x178F** [comment]
Hey @Anopy 
I have been busy with my projects. I'm sorry for the late reply. 

Maybe it will be fixed if an account is created with phone verification.

The definitive solution to this is to complete the logger in the project.

I don't have time for this.  Maybe i will finish it later. 

If you complete it before me, you will make a good contribution to the project and everyone will enjoy it.

Have a good day.

**Comment by UnMars** [comment]
Hey @0x178F 

I added a phone number verification to the script (should I make a PR ?) for each account but still barely all of them are being banned in few hours, being unusable before being banned.
Only like 1 accounts out of 10 created will works.
I think the main problem is the logger, if we got that we got all the project done.


If you don't have the time, could you explain me the fews lines of code you wrote about the logger or other stuff. I want to make it work :)

Thanks a lot and have a good day too !

**Comment by 0x178F** [comment]
Hey @Anopy 
It's totally your decision :)

Of course I can help, but there's not much I can tell you. Because I adapted it. I didn't go too far into the details of the logger. I just completed a small section. It was sending encrypted requests on the backend. I adapted the encryption method run by javascript to python. This was just the first part. Another reason they detect us is that we don't send fingerprints. Fingerprints are sent the same way, but their encryption is different. You can find the relevant codes in the react.registration.react.js file in Yandex. It's not that easy to solve, it's a bit complicated.
If you have any other questions, I'm happy to help.
